# Generated by Django 5.2.18 on 2026-10-09 12:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0.0"), max_digits=2
                    ),
                ),
                ("total_avaliacoes", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "vendedores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Peca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("tamanho", models.CharField(max_length=10)),
                ("tecido", models.CharField(max_length=80)),
                ("cor", models.CharField(max_length=40)),
                ("preco_original", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "tipo_defeito",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Estético"),
                            (2, "Funcional reparável"),
                            (3, "Funcional não reparável"),
                        ]
                    ),
                ),
                (
                    "localizacao_defeito",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Escondido"), (2, "Semivisível"), (3, "Visível")]
                    ),
                ),
                (
                    "extensao_defeito",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Pequena"), (2, "Média"), (3, "Grande")]
                    ),
                ),
                (
                    "local_detalhe",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="onde fica o defeito"
                    ),
                ),
                (
                    "medida_cm",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        verbose_name="medida do defeito (cm)",
                    ),
                ),
                ("descricao_defeito", models.TextField()),
                (
                    "aparece_vestida",
                    models.BooleanField(
                        default=False, verbose_name="defeito aparece com a peça vestida"
                    ),
                ),
                ("reparavel", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pecas",
                        to="pecas.vendedor",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
